import { NextResponse } from 'next/server';

type AdfNode = {
    type: string;
    version?: number;
    attrs?: Record<string, unknown>;
    content?: AdfNode[];
    text?: string;
    marks?: { type: string }[];
};

type JiraIssuePayload = {
    fields: {
        project: { key: string };
        summary: string;
        issuetype: { name: string };
        description: AdfNode;
        labels: string[];
        priority?: { name: string };
    };
};

// ── ADF Builder ─────────────────────────────────────────────────────────────
function normalizeJiraError(responseText: string, status: number): string {
    try {
        const errorJson = JSON.parse(responseText);
        const messages = Array.isArray(errorJson.errorMessages) ? errorJson.errorMessages : [];
        const errors = Object.entries(errorJson.errors || {}).map(([field, value]) => `${field}: ${String(value)}`);
        const combined = [...messages, ...errors].filter(Boolean).join(', ');
        if (combined) return `Jira rejected the request (${status}): ${combined}`;
    } catch {}

    if (status === 400) return 'Jira rejected the request. Check required fields, project key, issue type, and description format.';
    if (status === 401 || status === 403) return 'Jira authentication failed. Check Jira email, API token, and project permissions.';
    if (status === 404) return 'Jira project or endpoint was not found. Check Jira base URL and project key.';
    return `Jira API error ${status}. Check Jira settings and project permissions.`;
}

function toADF(text: string): AdfNode {
    const t = text?.trim() || '';

    // Detect code content anywhere in the text — check body lines after any header
    const bodyLines = t.split('\n');
    const bodyText = bodyLines.slice(5).join('\n'); // skip ~5 header lines
    const isJava = /\b(import\s+[a-z]|public\s+class|@Test|given\(\)\.when\(\)|RestAssured\.)\b/.test(bodyText || t);
    const isScenario = /^TC-\d+\s*\|/.test((bodyText || t).split('\n')[0] || '');
    const isJson = /^\s*\{[\s\S]*"(info|item|variable)"/.test((bodyText || t).trim());

    const codeLang = isJava ? 'java' : isJson ? 'json' : isScenario ? 'plain' : null;

    if (codeLang) {
        return {
            type: 'doc',
            version: 1,
            content: [
                ...(t.includes('Generated by')
                    ? [{ type: 'paragraph', content: [{ type: 'text', text: t.split('\n').slice(0, 3).join('\n') }] }]
                    : []),
                {
                    type: 'codeBlock',
                    attrs: { language: codeLang },
                    content: [{ type: 'text', text: (t.includes('Generated by') ? bodyText : t).trim().slice(0, 30000) }],
                },
            ],
        };
    }

    // Detect markdown table (manual test cases)
    const isTable = /^\|.+\|.+\|/.test(t.split('\n')[0] || '');
    if (isTable) {
        return {
            type: 'doc',
            version: 1,
            content: [
                {
                    type: 'codeBlock',
                    attrs: { language: 'markdown' },
                    content: [{ type: 'text', text: t.slice(0, 30000) }],
                },
            ],
        };
    }

    // Paragraph-based ADF for plain text
    const paragraphs = t.split(/\r?\n\r?\n/).map(p => p.replace(/\r?\n/g, ' ').trim()).filter(Boolean);
    return {
        type: 'doc',
        version: 1,
        content: paragraphs.length > 0
            ? paragraphs.map(p => ({ type: 'paragraph', content: [{ type: 'text', text: p }] }))
            : [{ type: 'paragraph', content: [] }],
    };
}

export async function POST(request: Request) {
    try {
        const {
            summary,
            description,
            issueType,
            priority,
            storyId,
            labels,
            credentials,
            traceability,
        } = await request.json();

        const baseUrl = credentials?.baseUrl || process.env.JIRA_BASE_URL;
        const email = credentials?.email || process.env.JIRA_EMAIL;
        const apiToken = credentials?.apiToken || process.env.JIRA_API_TOKEN;
        const projectKey = credentials?.projectKey || process.env.JIRA_PROJECT_KEY || 'TCGB';

        if (!baseUrl || !email || !apiToken || !projectKey) {
            return NextResponse.json(
                { success: false, error: 'Jira credentials not configured. Open Jira settings and save your credentials.' },
                { status: 400 }
            );
        }

        const normalizedUrl = baseUrl.startsWith('http') ? baseUrl : `https://${baseUrl}`;
        const auth = Buffer.from(`${email}:${apiToken}`).toString('base64');

        // Issue 4: Prepend [storyId] to summary if not already present
        let finalSummary = summary || 'No summary';
        if (storyId?.trim() && !finalSummary.startsWith('[')) {
            finalSummary = `[${storyId.trim()}] ${finalSummary}`;
        }

        // Issue 7: Detect code and use ADF codeBlock
        const adfDescription = toADF(description || 'No description provided');

        if (storyId) {
            adfDescription.content?.push({
                type: 'paragraph',
                content: [{ type: 'text', text: `Related Story: ${storyId}` }],
            });
        }

        const payload: JiraIssuePayload = {
            fields: {
                project: { key: projectKey },
                summary: finalSummary,
                issuetype: { name: issueType || 'Bug' },
                description: adfDescription,
                labels: Array.isArray(labels) ? labels : ['tcgen-buddy', 'qa-defect'],
            },
        };

        if (traceability?.sourceId) {
            payload.fields.description.content?.push({
                type: 'paragraph',
                content: [{ type: 'text', text: `Traceability: Source=${traceability.sourceId}${traceability.testCaseId ? ', TestCase=' + traceability.testCaseId : ''}` }],
            });
            const traceLabel = traceability.sourceId.toLowerCase().replace(/[^a-z0-9]/g, '-');
            if (!payload.fields.labels.includes(traceLabel)) {
                payload.fields.labels.push(traceLabel);
            }
        }

        if (priority) payload.fields.priority = { name: priority };

        console.log('[JIRA] Creating issue:', issueType, 'in project:', projectKey);

        const res = await fetch(`${normalizedUrl.replace(/\/$/, '')}/rest/api/3/issue`, {
            method: 'POST',
            headers: {
                Authorization: `Basic ${auth}`,
                'Content-Type': 'application/json',
                Accept: 'application/json',
            },
            body: JSON.stringify(payload),
        });

        const responseText = await res.text();
        console.log('[JIRA] Response status:', res.status);

        if (!res.ok) {
            return NextResponse.json({ success: false, error: normalizeJiraError(responseText, res.status) }, { status: res.status });
        }

        const data = JSON.parse(responseText);
        const issueKey = data.key;
        const issueUrl = `${normalizedUrl.replace(/\/$/, '')}/browse/${issueKey}`;

        // Create formal "Relates" link between new defect and parent story
        if (storyId?.trim() && issueKey) {
            try {
                const linkRes = await fetch(`${normalizedUrl.replace(/\/$/, '')}/rest/api/3/issueLink`, {
                    method: 'POST',
                    headers: {
                        Authorization: `Basic ${auth}`,
                        'Content-Type': 'application/json',
                        Accept: 'application/json',
                    },
                    body: JSON.stringify({
                        type: { name: 'Relates' },
                        inwardIssue:  { key: issueKey },
                        outwardIssue: { key: storyId.trim() },
                    }),
                });
                const linkBody = await linkRes.text();
                if (linkRes.ok || linkRes.status === 201) {
                    console.log(`[JIRA LINK] ✓ Linked defect ${issueKey} → Relates → ${storyId}`);
                } else {
                    console.warn(`[JIRA LINK] ✗ HTTP ${linkRes.status}:`, linkBody);
                }
            } catch (linkErr) {
                console.warn('[JIRA LINK ERROR]', linkErr);
            }
        }

        return NextResponse.json({ success: true, issueKey, issueUrl });

    } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        console.error('[JIRA ERROR]', msg);
        return NextResponse.json({ success: false, error: msg }, { status: 500 });
    }
}
