import { NextResponse } from 'next/server';

type AdfNode = {
    type: string;
    version?: number;
    attrs?: Record<string, unknown>;
    content?: AdfNode[];
    text?: string;
    marks?: { type: string }[];
};

type JiraIssuePayload = {
    fields: {
        project: { key: string };
        summary: string;
        issuetype: { name: string };
        description: AdfNode;
        labels: string[];
        priority?: { name: string };
    };
};

// ── Helpers ────────────────────────────────────────────────────────────────
function cleanBaseUrl(url: string) {
    return (url.startsWith('http') ? url : `https://${url}`).replace(/\/$/, '');
}

function buildAuth(email: string, apiToken: string) {
    return Buffer.from(`${email}:${apiToken}`).toString('base64');
}

// ── Extract exact Jira error message ──────────────────────────────────────
function extractJiraError(responseText: string, status: number): string {
    try {
        const errorJson = JSON.parse(responseText);
        const messages = Array.isArray(errorJson.errorMessages) ? errorJson.errorMessages : [];
        const errors = Object.entries(errorJson.errors || {}).map(([field, value]) => `${field}: ${String(value)}`);
        const combined = [...messages, ...errors].filter(Boolean).join(', ');
        if (combined) return `Jira API error (${status}): ${combined}`;
    } catch {}
    return `Jira API error (HTTP ${status}): ${responseText.slice(0, 500)}`;
}

function toADF(text: string): AdfNode {
    const t = text?.trim() || '';

    // Detect code content anywhere in the text — check body lines after any header
    const bodyLines = t.split('\n');
    const bodyText = bodyLines.slice(5).join('\n'); // skip ~5 header lines
    const isJava = /\b(import\s+[a-z]|public\s+class|@Test|given\(\)\.when\(\)|RestAssured\.)\b/.test(bodyText || t);
    const isScenario = /^TC-\d+\s*\|/.test((bodyText || t).split('\n')[0] || '');
    const isJson = /^\s*\{[\s\S]*"(info|item|variable)"/.test((bodyText || t).trim());

    const codeLang = isJava ? 'java' : isJson ? 'json' : isScenario ? 'plain' : null;

    if (codeLang) {
        return {
            type: 'doc',
            version: 1,
            content: [
                ...(t.includes('Generated by')
                    ? [{ type: 'paragraph', content: [{ type: 'text', text: t.split('\n').slice(0, 3).join('\n') }] }]
                    : []),
                {
                    type: 'codeBlock',
                    attrs: { language: codeLang },
                    content: [{ type: 'text', text: (t.includes('Generated by') ? bodyText : t).trim().slice(0, 30000) }],
                },
            ],
        };
    }

    // Detect markdown table (manual test cases)
    const isTable = /^\|.+\|.+\|/.test(t.split('\n')[0] || '');
    if (isTable) {
        return {
            type: 'doc',
            version: 1,
            content: [
                {
                    type: 'codeBlock',
                    attrs: { language: 'markdown' },
                    content: [{ type: 'text', text: t.slice(0, 30000) }],
                },
            ],
        };
    }

    // Paragraph-based ADF for plain text
    const paragraphs = t.split(/\r?\n\r?\n/).map(p => p.replace(/\r?\n/g, ' ').trim()).filter(Boolean);
    return {
        type: 'doc',
        version: 1,
        content: paragraphs.length > 0
            ? paragraphs.map(p => ({ type: 'paragraph', content: [{ type: 'text', text: p }] }))
            : [{ type: 'paragraph', content: [] }],
    };
}

export async function POST(request: Request) {
    try {
        const {
            summary,
            description,
            issueType,
            priority,
            storyId,
            labels,
            credentials,
            traceability,
        } = await request.json();

        const baseUrl = credentials?.baseUrl || process.env.JIRA_BASE_URL;
        const email = credentials?.email || process.env.JIRA_EMAIL;
        const apiToken = credentials?.apiToken || process.env.JIRA_API_TOKEN;
        const projectKey = credentials?.projectKey || process.env.JIRA_PROJECT_KEY || 'TCGB';

        if (!baseUrl || !email || !apiToken || !projectKey) {
            return NextResponse.json(
                { success: false, error: 'Jira credentials not configured. Open Jira settings and save your credentials.' },
                { status: 400 }
            );
        }

        const normalizedUrl = cleanBaseUrl(baseUrl);
        const auth = buildAuth(email, apiToken);
        const resolvedIssueType = issueType || 'Bug';

        // ── Log pre-creation details ─────────────────────────────────────
        console.log('[JIRA CREATE] --- Pre-creation audit ---');
        console.log('[JIRA CREATE] Base URL:', normalizedUrl);
        console.log('[JIRA CREATE] Project Key:', projectKey);
        console.log('[JIRA CREATE] Issue Type:', resolvedIssueType);
        console.log('[JIRA CREATE] Parent Story ID:', storyId || '(none)');
        console.log('[JIRA CREATE] Auth user email:', email);

        // ── Step 1: Validate project exists ──────────────────────────────
        console.log('[JIRA CREATE] Validating project:', projectKey);
        const projectRes = await fetch(`${normalizedUrl}/rest/api/3/project/${encodeURIComponent(projectKey)}`, {
            headers: {
                Authorization: `Basic ${auth}`,
                Accept: 'application/json',
            },
        });
        const projectText = await projectRes.text();

        if (!projectRes.ok) {
            const errorMsg = extractJiraError(projectText, projectRes.status);
            console.warn('[JIRA CREATE] Project validation failed:', projectRes.status, errorMsg);
            return NextResponse.json(
                { success: false, error: `Project validation failed: ${errorMsg}` },
                { status: projectRes.status }
            );
        }
        console.log('[JIRA CREATE] Project exists ✓');

        // ── Step 2: Verify issue type exists ─────────────────────────────
        console.log('[JIRA CREATE] Validating issue type:', resolvedIssueType);
        const issuetypeRes = await fetch(`${normalizedUrl}/rest/api/3/issuetype`, {
            headers: {
                Authorization: `Basic ${auth}`,
                Accept: 'application/json',
            },
        });
        const issuetypeText = await issuetypeRes.text();

        if (!issuetypeRes.ok) {
            const errorMsg = extractJiraError(issuetypeText, issuetypeRes.status);
            console.warn('[JIRA CREATE] Issue type lookup failed:', issuetypeRes.status, errorMsg);
            return NextResponse.json(
                { success: false, error: `Issue type lookup failed: ${errorMsg}` },
                { status: issuetypeRes.status }
            );
        }

        let issuetypeData: { name?: string }[];
        try {
            issuetypeData = JSON.parse(issuetypeText);
        } catch {
            return NextResponse.json(
                { success: false, error: 'Issue type endpoint returned an invalid response.' },
                { status: 502 }
            );
        }

        const typeExists = issuetypeData.some(
            (t: { name?: string }) => t.name?.toLowerCase() === resolvedIssueType.toLowerCase()
        );
        if (!typeExists) {
            const available = issuetypeData.map((t: { name?: string }) => t.name || '?').join(', ');
            return NextResponse.json(
                {
                    success: false,
                    error: `Issue type "${resolvedIssueType}" does not exist in this Jira instance. Available types: ${available}`,
                },
                { status: 400 }
            );
        }
        console.log('[JIRA CREATE] Issue type exists ✓');

        // ── Step 3: Verify create permission via createmeta ──────────────
        console.log('[JIRA CREATE] Checking create permission for', projectKey);
        const createmetaRes = await fetch(
            `${normalizedUrl}/rest/api/3/issue/createmeta?projectKeys=${encodeURIComponent(projectKey)}&expand=projects.issuetypes`,
            {
                headers: {
                    Authorization: `Basic ${auth}`,
                    Accept: 'application/json',
                },
            }
        );
        const createmetaText = await createmetaRes.text();

        if (!createmetaRes.ok) {
            const errorMsg = extractJiraError(createmetaText, createmetaRes.status);
            console.warn('[JIRA CREATE] Permission check failed:', createmetaRes.status, errorMsg);
            return NextResponse.json(
                { success: false, error: `Permission check failed: ${errorMsg}` },
                { status: createmetaRes.status }
            );
        }

        let createmetaData: { projects?: { key?: string; issuetypes?: { name?: string; subtask?: boolean }[] }[] };
        try {
            createmetaData = JSON.parse(createmetaText);
        } catch {
            return NextResponse.json(
                { success: false, error: 'Permission check returned an invalid response.' },
                { status: 502 }
            );
        }

        const projectMeta = createmetaData.projects?.find(
            (p) => p.key?.toUpperCase() === projectKey.toUpperCase()
        );
        const creatableTypes = projectMeta?.issuetypes
            ?.filter((t) => !t.subtask)
            .map((t) => t.name) || [];

        if (!projectMeta || creatableTypes.length === 0) {
            return NextResponse.json(
                {
                    success: false,
                    error: `User does not have permission to create issues in project "${projectKey}". Check Jira project permissions and issue type availability.`,
                },
                { status: 403 }
            );
        }

        if (!creatableTypes.some((t) => t?.toLowerCase() === resolvedIssueType.toLowerCase())) {
            return NextResponse.json(
                {
                    success: false,
                    error: `Issue type "${resolvedIssueType}" is not available for project "${projectKey}". Available creatable types: ${creatableTypes.join(', ')}`,
                },
                { status: 400 }
            );
        }
        console.log('[JIRA CREATE] Create permission confirmed ✓');

        // ── All validations passed — build payload ───────────────────────
        let finalSummary = summary || 'No summary';
        if (storyId?.trim() && !finalSummary.startsWith('[')) {
            finalSummary = `[${storyId.trim()}] ${finalSummary}`;
        }

        const adfDescription = toADF(description || 'No description provided');

        if (storyId) {
            adfDescription.content?.push({
                type: 'paragraph',
                content: [{ type: 'text', text: `Related Story: ${storyId}` }],
            });
        }

        const payload: JiraIssuePayload = {
            fields: {
                project: { key: projectKey },
                summary: finalSummary,
                issuetype: { name: resolvedIssueType },
                description: adfDescription,
                labels: Array.isArray(labels) ? labels : ['tcgen-buddy', 'qa-defect'],
            },
        };

        if (traceability?.sourceId) {
            payload.fields.description.content?.push({
                type: 'paragraph',
                content: [{ type: 'text', text: `Traceability: Source=${traceability.sourceId}${traceability.testCaseId ? ', TestCase=' + traceability.testCaseId : ''}` }],
            });
            const traceLabel = traceability.sourceId.toLowerCase().replace(/[^a-z0-9]/g, '-');
            if (!payload.fields.labels.includes(traceLabel)) {
                payload.fields.labels.push(traceLabel);
            }
        }

        if (priority) payload.fields.priority = { name: priority };

        // ── Create the issue ──────────────────────────────────────────────
        console.log('[JIRA CREATE] Creating issue...');
        const res = await fetch(`${normalizedUrl}/rest/api/3/issue`, {
            method: 'POST',
            headers: {
                Authorization: `Basic ${auth}`,
                'Content-Type': 'application/json',
                Accept: 'application/json',
            },
            body: JSON.stringify(payload),
        });

        const responseText = await res.text();

        if (!res.ok) {
            const exactError = extractJiraError(responseText, res.status);
            console.warn('[JIRA CREATE] Create failed:', res.status, exactError);
            return NextResponse.json({ success: false, error: exactError }, { status: res.status });
        }

        const data = JSON.parse(responseText);
        const issueKey = data.key;
        const issueUrl = `${normalizedUrl}/browse/${issueKey}`;

        console.log('[JIRA CREATE] Created:', issueKey);

        // ── Link to parent story ─────────────────────────────────────────
        if (storyId?.trim() && issueKey) {
            try {
                const linkRes = await fetch(`${normalizedUrl}/rest/api/3/issueLink`, {
                    method: 'POST',
                    headers: {
                        Authorization: `Basic ${auth}`,
                        'Content-Type': 'application/json',
                        Accept: 'application/json',
                    },
                    body: JSON.stringify({
                        type: { name: 'Relates' },
                        inwardIssue:  { key: issueKey },
                        outwardIssue: { key: storyId.trim() },
                    }),
                });
                const linkBody = await linkRes.text();
                if (linkRes.ok || linkRes.status === 201) {
                    console.log(`[JIRA LINK] ✓ Linked defect ${issueKey} → Relates → ${storyId}`);
                } else {
                    console.warn(`[JIRA LINK] ✗ HTTP ${linkRes.status}:`, linkBody);
                }
            } catch (linkErr) {
                console.warn('[JIRA LINK ERROR]', linkErr);
            }
        }

        return NextResponse.json({ success: true, issueKey, issueUrl });

    } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        console.error('[JIRA ERROR]', msg);
        return NextResponse.json({ success: false, error: msg }, { status: 500 });
    }
}
